### ISSUE TITLE
Options of ports and make.conf

### ISSUE THREAD

**Issue by czkarex** [cbsd/modules-cpr#1]
Hi, I would like to start using cpr instead of Poudriere. I prepared a new installation of freebsd 13.2, current cbsd + cpr module. I can create packages, but I can't affect options. Not even with make.conf, and the initial port settings don't work either - even with a new jail it doesn't prompt me to set options of ports. Thanks, Karel

**Comment by olevole** [comment]
Hi. Wow! I don't think this script can replace `poudriere`, since it is mainly designed for my internal tasks/purposes ;-)

At least I didn’t set myself the task of replacing the poudriere (which I also use, together with `cbsd cpr`)

However, this script must be able to use options. I forgot to return 'make.conf' file usage and `make config-recursive` . This should be fixed now: Try to update/get fixes via:
```
cbsd module mode=upgrade cpr
```

With `cbsd cpr` script you have two options to adjust options:

1) Interactive. When you run the build for the first time for 'xxx.list' job, the script calls 'config-recursive' where  you can configure the options you need through the usual bsddialog. All options are saved in `/var/db/ports-cprXXX` directory (on the host). So if you want to change the option you can do it directly via `/var/db/ports-cprXXX/` or login into `cprXXX`  jail and get the options dialog in the usual way for the port you need, e.g.:

```
make -C /usr/ports/misc/mc config
```

If you want to reset all previously entered options - you can simply delete `/var/db/ports-cprXXX` - the next time you run the script, it will show you the dialog again


2) Via custom make.conf. E.g.:

```
echo "/usr/ports/misc/mc" > /tmp/myrepo.list

cat > /tmp/myrepo_make.conf <<EOF
OPTIONS_UNSET+= NLS
OPTIONS_UNSET+= EXAMPLES
OPTIONS_UNSET+= DOCS
OPTIONS_UNSET+= MAN
OPTIONS_UNSET+= X11
OPTIONS_UNSET+= MANPAGES
EOF
```

```
cbsd cpr pkglist=/tmp/myrepo.list dstdir=/tmp/myrepo makeconf=/tmp/myrepo_make.conf
```

(also you can add 'batch=1` to prevent dialog)

**Comment by olevole** [comment]
Feel free to re-open, if you have any questions or suggestions. Feedback is very valuable for CBSD!
